version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ktaxes
      POSTGRES_USER: godou
      POSTGRES_PASSWORD: 1111
    ports:
      - "2000:5432"
    volumes:
      - ou_ktax:/var/lib/postgresql/data

volumes:
  ou_ktax:
    driver: local
